AWSTemplateFormatVersion: '2010-09-09'
Description: A-New-Startup EKS - Backend services needed by the code - DDB/SNS/SQS

Parameters:
  Prefix:
    Type: String
    Default: a-new-startup-eks
    Description: "A Prefix to use on the resource names."

Resources:
  StartupSignupsTable:
    Type: AWS::DynamoDB::Table
    Description: A simple key/value table to store the info for anyone interested in our startup.
    Properties:
      BillingMode: 'PAY_PER_REQUEST'
      AttributeDefinitions:
        -
          AttributeName: email
          AttributeType: S
      KeySchema:
        - 
          AttributeName: email
          KeyType: HASH 
  
  NewSignupQueue: 
    Type: AWS::SQS::Queue
      
  NewSignupTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - Endpoint:
          Fn::GetAtt: [NewSignupQueue, Arn]
        Protocol: sqs

  AllowSNS2SQSPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: PublicationPolicy
        Statement:
        - Action: ['sqs:SendMessage']
          Condition:
            ArnEquals:
              aws:SourceArn: {Ref: NewSignupTopic}
          Effect: Allow
          Principal: {AWS: '*'}
          Resource:
            Fn::GetAtt: [NewSignupQueue, Arn]
          Sid: Allow-SNS-SendMessage
        Version: '2008-10-17'
      Queues:
      - {Ref: NewSignupQueue}
  
Outputs

  TableName:
    Value: !Ref StartupSignupsTable
    Export:
      Name: !Join ['-', [!Ref Prefix, 'TableName']]
      
  TopicArn:
    Value: !Ref NewSignupTopic
    Export:
      Name: !Join ['-', [!Ref Prefix, 'TopicArn']]

  QueueArn:
    Value: !GetAtt NewSignupQueue.Arn
    Export:
      Name: !Join ['-', [!Ref Prefix, 'QueueArn']]
