accountId: "123456789012"
region: "us-east-1"
repoName: "a-new-startup-eks"
tableName: "a-new-startup-dev"
topicArn: "arn:aws:sns:us-east-1:123456789012:a-new-startup-dev"
imageTag: "000000"
namespace: "a-new-startup"