apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # NOTE: Best practice with a helm chart is to specify namespace using --namespace option
  namespace: "{{ .Release.Namespace }}"
  name: ingress-a-new-startup
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-a-new-startup
                port:
                  number: 80