apiVersion: v1
kind: Service
metadata:
  # NOTE: Best practice with a helm chart is to specify namespace using --namespace option
  namespace: "{{ .Release.Namespace }}"
  name: lb-a-new-startup
spec:
  type: LoadBalancer
  selector:
    app: a-new-startup
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
