apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-a-new-startup"
  namespace: a-new-startup 
  labels:
    app: "{{ .Values.namespace }}"
spec:
  replicas: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: a-new-startup
  template:
    metadata:
      labels:
        app: a-new-startup
    spec:
      # Run using a serviceaccount (IRSA) so we can get access to DDB/SNS
      serviceAccountName: {{ .Values.svcAccount }}
      # Do not run as root - that's a bad practice
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      containers:
      - name: nodejs-app
        image: "{{ .Values.accountId }}.dkr.ecr.{{ .Values.region }}.amazonaws.com/{{ .Values.repoName }}:{{ .Values.imageTag }}"
        ports:
        - containerPort: 3000
        env:
        - name: APP_TABLE_NAME
          value: {{ .Values.tableName | quote }}
        - name: APP_TOPIC_ARN
          value: "{{ .Values.topicArn }}"
        - name: REGION
          value: "{{ .Values.region }}"
          # The code will see this and run with AWS-Xray-Sdk in use.
        - name: XRAY
          value: "ON"
      - name: x-ray-daemon
        image: public.ecr.aws/xray/aws-xray-daemon:latest
        ports: 
        - containerPort: 2000
        # Need to set this because IMDS not available on Fargate 
        env:
        - name: AWS_REGION
          value: "{{ .Values.region }}"
